### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by arkag** [tobiasvl/1password2pass#2]
This is still with my password store, but isn't giving me an error related to my actual data...

Here is my ruby version:

```
ishmael@aegislash:~/logins.1pif|⇒  ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
```

It seems to be failing at this line:

```
{"uuid":"EF22EAF83D4547E5A027DBF5F0196B71","updatedAt":1455422946,"securityLevel":"SL5","contentsHash":"89fa4e6c","title":"Login","secureContents":{},"txTimestamp":1456083029,"createdAt":1455422941,"typeName":"webforms.WebForm"}
***5642bee8-a5ff-11dc-8314-0800200c9a66***
```

Which doesn't make sense because that's a blank password. Why does 1password have garbage entries?

Here is my error:

```
/usr/local/lib/node_modules/1password2pass/lib/parse.js:26
                i.secureContents.fields.forEach(function(field) {
                                       ^

TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/1password2pass/lib/parse.js:26:40
    at Array.forEach (native)
    at module.exports (/usr/local/lib/node_modules/1password2pass/lib/parse.js:11:11)
    at module.exports (/usr/local/lib/node_modules/1password2pass/lib/index.js:21:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/1password2pass/bin/1password2pass:5:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

**Comment by arkag** [comment]
It's definitely because of the garbage entry... God I'm so glad that I'm moving to pass....

**Comment by tobiasvl** [comment]
Weird. I can definitely handle this in my importer though. No reason not to!

**Comment by arkag** [comment]
I think this could also be related to the fact that I was running the incorrect script... That output very well might be from the old script, which I have since deleted.

**Comment by tobiasvl** [comment]
Closing this, please reopen if it is reproduced.
